-- SQL Query to setup Supabase for Dragoz Events
-- Run this in your Supabase SQL Editor: https://supabase.com/dashboard/project/_/sql

CREATE TABLE IF NOT EXISTS event_registrations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    college TEXT NOT NULL,
    department TEXT NOT NULL,
    event_name TEXT NOT NULL
);

-- Enable Row Level Security (RLS)
ALTER TABLE event_registrations ENABLE ROW LEVEL SECURITY;

-- Create policy to allow anyone to register (Insert)
CREATE POLICY "Allow public insert registrations" 
ON event_registrations FOR INSERT 
WITH CHECK (true);

-- Create policy to allow access to registrations (Select) for admin console
CREATE POLICY "Allow public select registrations" 
ON event_registrations FOR SELECT 
USING (true);
